src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>birthdate__c</fullName>
        <description>birthdate</description>
        <inlineHelpText>birthdate</inlineHelpText>
        <label>birthdate</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Joint_contact_Id__c</fullName>
        <description>Joint Contact Id</description>
        <inlineHelpText>Joint Contact Id</inlineHelpText>
        <label>Joint_contact_Id</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Primary_Contact__c</description>
        <inlineHelpText>Primary_Contact__c</inlineHelpText>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ApplicationType__c</fullName>
        <description>ApplicationType for phone registration</description>
        <inlineHelpText>ApplicationType for phone registration</inlineHelpText>
        <label>ApplicationType</label>
        <picklist>
            <picklistValues>
                <fullName>Single</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Joint</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Birthdate_second_contact__c</fullName>
        <description>Birthdate_second_contact</description>
        <inlineHelpText>Birthdate_second_contact</inlineHelpText>
        <label>Birthdate_second_contact</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_second_contact__c</fullName>
        <description>Email_second_contact</description>
        <inlineHelpText>Email_second_contact</inlineHelpText>
        <label>Email_second_contact</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone_second_contact__c</fullName>
        <description>Phone_second_contact</description>
        <inlineHelpText>Phone_second_contact</inlineHelpText>
        <label>Phone_second_contact</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Salutation_second_contact__c</fullName>
        <label>Salutation_second_contact</label>
        <picklist>
            <picklistValues>
                <fullName>Adv.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Er.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>God.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hon.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M/s.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mrs.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ms.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Second_contact_FirstName__c</fullName>
        <description>Second_contact_FirstName</description>
        <inlineHelpText>Second_contact_FirstName</inlineHelpText>
        <label>Second_contact_FirstName</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Second_contact_LastName__c</fullName>
        <description>Second_contact_LastName</description>
        <inlineHelpText>Second_contact_LastName</inlineHelpText>
        <label>Second_contact_LastName</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>birthdate__c</fullName>
        <description>birthdate</description>
        <inlineHelpText>birthdate</inlineHelpText>
        <label>birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <description>Type of the lead</description>
        <inlineHelpText>Type of the lead</inlineHelpText>
        <label>type</label>
        <picklist>
            <picklistValues>
                <fullName>Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/leadDemo.cls
public with sharing class leadDemo
{

    public Lead lead{get;set;}
    public List<contact> primarycon{get;set;}
    public id accid{get;set;}
    public account accdetails{get;set;}
    
    
    public leadDemo(ApexPages.StandardController controller) {
        accid=ApexPages.currentpage().getparameters().get('id');
        lead = new Lead();
       // primarycon = new contact();
        controllermethod();

    }







public void controllermethod()
{

primarycon=[select salutation,firstname,joint_contact_id__c,primary_Contact__c,lastname,birthdate,mailingstreet,mailingcity,mailingstate,mailingcountry,mailingpostalcode,phone,mobilephone,email,title from contact where accountid=:accid];
accdetails = [select name from account where id=:accid];
        lead.type__c='Registration';
        lead.company=accdetails.name;
System.debug('Lead company:'+lead.company);
        //lead.applicationtype__c='single';
        for(Contact con:primarycon)
        {
        if(con.primary_Contact__c==true)
        {
        lead.salutation=con.salutation;
        lead.firstname=con.firstname;
        lead.lastname=con.lastname;
        lead.birthdate__c=con.birthdate;
        lead.street=con.mailingstreet;
        lead.city=con.mailingcity;
        lead.state=con.mailingstate;
        lead.country=con.mailingcountry;
        lead.postalcode=con.mailingpostalcode;
        lead.phone=con.phone;
        lead.mobilephone=con.mobilephone;
        lead.title=con.title;
        lead.email=con.email;
    }
    else
    {
            lead.salutation_second_contact__c= con.salutation;
            lead.second_Contact_firstname__c=con.firstname;
            lead.second_Contact_lastname__c=con.lastname;
            lead.Birthdate_second_contact__c=con.Birthdate;
            lead.phone_second_Contact__c=con.phone;
            lead.email_second_contact__c=con.email;
    }
 }   
}

public void SaveLead()
{
insert lead;
redirect();
}

public PageReference redirect()
    {
        PageReference pr = new PageReference('https://ap2.salesforce.com/'+accid);
        pr.setredirect(true);
        return pr;
        
    }

}