src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>email__c</fullName>
        <description>email</description>
        <inlineHelpText>email</inlineHelpText>
        <label>email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Division__c.object
<CustomObject>
    <description>Divisions that comes under certain classes/standards</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>Class with which this division is associated with</description>
        <inlineHelpText>Class with which this division is associated with</inlineHelpText>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Divisions</relationshipLabel>
        <relationshipName>Divisions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Division</label>
    <nameField>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Class/Standard in which student currently belongs</description>
        <inlineHelpText>Class/Standard in which student currently belongs</inlineHelpText>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Division in which the student currently belongs to</description>
        <inlineHelpText>Division in which the student currently belongs to</inlineHelpText>
        <label>Division</label>
        <referenceTo>Division__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>Mobile of the student</description>
        <inlineHelpText>Mobile of the Student</inlineHelpText>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Phone of the student</description>
        <inlineHelpText>Phone of the student</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <description>Email of the student</description>
        <inlineHelpText>Email of the student</inlineHelpText>
        <label>email</label>
        <type>Email</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StudentController.cls
public class StudentController
{

    //public void showLimitedRecords{get;set;}
   // public List<Student__c> stdlst {get;set;}
  
  //  public List<Student__c> studentsToShow{get;set;}
    //public String getSelectedRange{get;set;}
    //public List<Student__c> showLimitedRecords{get;set;} 
    
     public List<Opportunity> stdlst {get;set;}
     public List<Opportunity> studentsToShow{get;set;}
    public String getSelectedRange{get;set;}
    public List<Opportunity> showLimitedRecords{get;set;} 
    public boolean hidePreviousPage{get;set;}
    
    public integer counter{get;set;}
    public integer limitsize{get;set;}
    public integer totalsize{get;set;}
    public integer selectedrange{get;set;}
    
    public StudentController()
    {
    
    counter=0;
    limitsize=0;
    totalsize=0;
    selectedrange=0;
    
   // stdlst = new List<Student__c>();
   stdlst = new List<Opportunity>();
     //stdlst = [select first_name__c,last_name__c,email__c,phone__c,mobile__c,class__r.name,division__c from Student__c];
     stdlst=[select name,amount,account.name,stagename from opportunity];
     //studentsToShow = new List<Student__c>();
     studentsToShow = new List<Opportunity>();
     totalsize=stdlst.size();
     for(integer i=0;i<10;i++)
         {
                studentsToShow.add(stdlst.get(i));
         }
     
    }
    
    public PageReference showLimitedRecords()
    {
    
    studentsToShow.clear();
    System.debug('In showLimitedRecords');
    System.debug('getSelectedRange:'+getSelectedRange);
    selectedrange = Integer.valueOf(getSelectedRange);
       System.debug('selected Range:'+selectedrange);
       System.debug('2nd element of the list:'+stdlst.get(2));
       if(selectedrange<totalsize)
       {
         for(integer i=0;i<selectedrange;i++)
         {
                studentsToShow.add(stdlst.get(i));
         }
        }
        else
        {
            for(integer i=0;i<totalsize;i++)
         {
         System.debug('i is:'+i);
                studentsToShow.add(stdlst.get(i));
         }
        
        } 
         System.debug('studentsToShow size:'+studentsToShow.size());
         return null;
    }
    
    
    public void ShowFirstPage()
    {
             counter=0;
       studentsToShow.clear();
       
       if((counter+limitsize)<=totalsize)
       {
         for(integer i=0;i<limitsize;i++)
         {
                studentsToShow.add(stdlst.get(i));
         }
        }
        else
        {
            for(integer i=0;i<totalsize;i++)
         {
         System.debug('i is:'+i);
                studentsToShow.add(stdlst.get(i));
         }
        
        } 
    
    hidePreviousPage=false;
    
    }
    
    
    public PageReference ShowNextPage()
    {
             System.debug('In Next Page Method');
       studentsToShow.clear();
       limitsize= Integer.valueOf(getSelectedRange);
       counter+=limitsize;
       System.debug('counter is:'+counter);
       if((counter+limitsize)<totalsize)
       {
       System.debug('in NextPage If:');
         for(integer i=counter;i<(counter+limitsize);i++)
         {
                studentsToShow.add(stdlst.get(i));
         }
        }
        else
        {
            for(integer i=0;i<totalsize;i++)
         {
         System.debug('i is:'+i);
                studentsToShow.add(stdlst.get(i));
         }
        
        }
        System.debug('list size is:'+studentsToShow.size());
        System.debug('List is:'+studentsToShow); 
          hidePreviousPage=true;
    return null;
    }
    
    public PageReference ShowPreviousPage()
    {
             System.debug('In Previous Page Method');
       studentsToShow.clear();
       limitsize= Integer.valueOf(getSelectedRange);
       counter-=limitsize;
       System.debug('counter is:'+counter);
       if((counter+limitsize)<totalsize)
       {
       System.debug('in NextPage If:');
         for(integer i=counter;i<(counter+limitsize);i++)
         {
                studentsToShow.add(stdlst.get(i));
         }
        }
        else
        {
            for(integer i=0;i<totalsize;i++)
         {
         System.debug('i is:'+i);
                studentsToShow.add(stdlst.get(i));
         }
        
        }
        System.debug('list size is:'+studentsToShow.size());
        System.debug('List is:'+studentsToShow); 
    return null;
    }
    
    
    public PageReference ShowLastPage()
    {
             System.debug('In Previous Page Method');
       studentsToShow.clear();
       limitsize= Integer.valueOf(getSelectedRange);
       counter=totalsize-limitsize;
       System.debug('counter is:'+counter);
       
        
            for(integer i=counter;i<totalsize;i++)
         {
         System.debug('i is:'+i);
                studentsToShow.add(stdlst.get(i));
         }
        
        
        System.debug('list size is:'+studentsToShow.size());
        System.debug('List is:'+studentsToShow); 
        hidePreviousPage=true;
    return null;
    }
    
}