src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>email__c</fullName>
        <description>email</description>
        <inlineHelpText>email</inlineHelpText>
        <label>email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Primary_Contact__c</description>
        <inlineHelpText>Primary_Contact__c</inlineHelpText>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContactTriggerHelper.cls
public class ContactTriggerHelper
{
    public void updateaccount(List<contact> contacts) 
    {
    List<account> accounts  = [select id,email__c,phone from account];
    List<account> updatedaccounts = new List<account>();
        for(Contact contact:contacts)
        {
            for(account acc:accounts)
            {
                if(contact.AccountId.equals(acc.id) && contact.primary_contact__c==true)
                {
                    acc.email__c=contact.email;
                    acc.phone=contact.phone;
                    updatedaccounts.add(acc); 
                }
            }
        }
        update updatedaccounts ;
    }
}