src/objects/Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Absent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked, if student is absent</description>
        <inlineHelpText>Checked, if student is absent</inlineHelpText>
        <label>Absent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related class to this attendance report</description>
        <inlineHelpText>Related class to this attendance report</inlineHelpText>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Attendances</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Division to this attendance</description>
        <inlineHelpText>Related Division to this attendance</inlineHelpText>
        <label>Division</label>
        <referenceTo>Division__c</referenceTo>
        <relationshipLabel>Attendances</relationshipLabel>
        <relationshipName>Attendances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Present__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked, i f student is present for the day</description>
        <inlineHelpText>Checked, i f student is present for the day</inlineHelpText>
        <label>Present</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_if_Absent__c</fullName>
        <description>Reason for absent</description>
        <inlineHelpText>Reason for absent</inlineHelpText>
        <label>Reason, if Absent</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>StudentName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related student of this attendance report</description>
        <inlineHelpText>Related student of this attendance report</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Attendances</relationshipLabel>
        <relationshipName>Attendances</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <label>Attendance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Division__c.object
<CustomObject>
    <description>Divisions that comes under certain classes/standards</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>Class with which this division is associated with</description>
        <inlineHelpText>Class with which this division is associated with</inlineHelpText>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Divisions</relationshipLabel>
        <relationshipName>Divisions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>attendance_reported__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Will be checked on when attendance for the day is reported. User will not be able to re-report the attendance for the same day for the same division, if this is checked</description>
        <inlineHelpText>Will be checked on when attendance for the day is reported. User will not be able to re-report the attendance for the same day for the same division, if this is checked</inlineHelpText>
        <label>attendance reported</label>
        <type>Checkbox</type>
    </fields>
    <label>Division</label>
    <nameField>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Class/Standard in which student currently belongs</description>
        <inlineHelpText>Class/Standard in which student currently belongs</inlineHelpText>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Division in which the student currently belongs to</description>
        <inlineHelpText>Division in which the student currently belongs to</inlineHelpText>
        <label>Division</label>
        <referenceTo>Division__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/attendanceController.cls
public class attendanceController
{
        public Date dateFilter {get;set;}

        public String id{get;set;}
        public boolean showselectionblock {get;set;}
        public boolean showAttendanceTable {get;set;}
        public boolean showTable{get;set;}
        public String title{get;set;}    

        public List<selectOption> classVals{get;set;}
        public List<selectOption> divVals{get;set;}

        public List<SelectOption> cls_options{get;set;}
        public List<SelectOption> div_options{get;set;}
        public List<division__c> divisionnames{get;set;}
        public division__c div {get;set;}
        public Set<String> divisions{get;set;}
        public Set<String> classes{get;set;}
        public String classPlaceHolder{get;set;}
        public String divPlaceHolder{get;set;}
        public list<Student__c> stdlst{get;set;}
        public list<attendance__c> attendancelst {get;set;}
        public String classid{get;set;}
        
        public PageReference LoadStudents{get;set;}
        public PageReference SaveAttendance{get;set;}
        public PageReference showAttendnaceReport{get;set;}
        
        public List<attendance__c> attendancereport{get;set;}
            
    public attendanceController()
    {
        dateFilter =  System.Today();
        
        
        id = ApexPages.CurrentPage().getParameters().get('id');
        classid= ApexPages.CurrentPage().getParameters().get('class');
        System.debug('id is:'+id);
        System.debug('class is:'+classid);
        
        showAttendanceTable=false;
        showTable = false;
        if(id!=null)
        {
        
            title='Aattendance Report - '+System.today();
            showselectionblock = false;
            
           // div = [select class__c from division__C where id=:id];
            LoadStudents();
        }
        else
        {
            showselectionblock = true;
            title = 'Select class and division';
            classVals();
            divvals();
        }
        
    }
    
    public List<SelectOption> classVals()
    {
        cls_options = new List<SelectOption>();
        div_options = new List<SelectOption>();
        divisionnames = [select name,class__r.name from division__c];
        
        Set<String> divisions = new Set<String>();
        Set<String> classes = new Set<String>();
        
        for(division__c div:divisionnames)
        {
                divisions.add(div.name);
                classes.add(div.class__r.name);    
        }
        
        for(String cls:classes)
        {
            cls_options.add(new SelectOption(cls,cls));
        }
        cls_options.sort();
        System.debug('cls is:'+cls_options);        

        return cls_options;
        
    }
    
    public List<SelectOption> divVals()
    {
        
        div_options = new List<SelectOption>();
                
        Set<String> divisions = new Set<String>();
        
        for(division__c div:divisionnames)
        {
                divisions.add(div.name);
        }
        
                
        for(String divs:divisions)
        {
             div_options.add(new SelectOption(divs,divs));
             
        }
        div_options.sort();
              System.debug('divs is:'+div_options);        
        return div_options;
    }
    
    public PageReference LoadStudents()
    {
    
    showAttendanceTable=true;
    attendancelst = new List<attendance__c>();
    
    if(id==null)
    {
        stdlst = [select id,name,class__c,division__c from student__c where class__r.name=:classPlaceHolder and division__r.name=:divPlaceHolder];
    }
     else
     {
         stdlst = [select id,name,class__c,division__c from student__c where class__c=:classid and division__c=:id];
     }  
                for(integer i=0;i<stdlst.size();i++)
                {
                    attendance__c atnd = new attendance__c(studentname__c=stdlst[i].id,absent__c=false,present__c=false,reason_if_absent__c='',name=String.valueOf(System.today()),class__c=stdlst[i].class__c,division__c=stdlst[i].division__c);
                    attendancelst.add(atnd);
             
        }
        
        return null;
    }
   
    public PageReference SaveAttendance()
    {
    
          for(attendance__c atend:attendancelst)
          {
              System.debug('Student:'+atend.studentname__c+'Present:'+atend.present__c);
              System.debug('Student:'+atend.studentname__c+'Absent:'+atend.absent__c);
          }
    
         insert attendancelst;
                     
         division__c divs = [select attendance_reported__c from division__c where id=:id];
         divs.attendance_reported__c = true;
         update divs;
         
            PageReference pr = new PageReference(System.Label.RA_ReDirectToDivision+stdlst[0].division__c);
            pr.setRedirect(true);
            return pr;
    }
    
    public PageReference showAttendnaceReport()
    {
    
        showTable=true;
    
   // Datetime dt = datetime.newInstance(dateFilter.year(), dateFilter.month(),dateFilter.day());
   // System.debug('Only Date is:'+dt);
           attendancereport = [select name,studentname__r.name,present__c,absent__c,reason_if_absent__c from attendance__c where class__r.name=:classPlaceHolder and division__r.name=:divPlaceHolder and name=:String.valueOf(dateFilter)];
                return null;
                
    }
    
}