src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the candidate</description>
        <externalId>true</externalId>
        <inlineHelpText>Email of the candidate</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First Name of the candidate</description>
        <externalId>true</externalId>
        <inlineHelpText>First Name of the candidate</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last Name of the candidate</description>
        <externalId>true</externalId>
        <inlineHelpText>Last Name of the candidate</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Candidate_detail_verification.cls
public class Candidate_detail_verification {

    List<Candidate__c> ca;
    
    public Candidate_detail_verification(List<Candidate__c> c1)
    {
        ca=c1;
    }
       
    public void check()
    {System.debug('in check');
        for(Candidate__c c2: ca)
        {
        if(String.isBlank(c2.first_name__c) && String.isBlank(c2.last_name__c) && String.isBlank(c2.email__c))
        {
            System.debug('in if of check');
                    c2.addError('Please ,provide first name,last name and email');
        }
        }
    }
    
}