src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions</description>
    <fields>
        <fullName>City__c</fullName>
        <description>City of the candidate</description>
        <inlineHelpText>City of the candidate</inlineHelpText>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currently_Employeed__c</fullName>
        <defaultValue>true</defaultValue>
        <description>checked-currently employed
unchecked- not currently employed</description>
        <inlineHelpText>checked-currently employed
unchecked- not currently employed</inlineHelpText>
        <label>Currently Employed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the candidate</description>
        <externalId>true</externalId>
        <inlineHelpText>Email of the candidate</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First Name of the candidate</description>
        <externalId>true</externalId>
        <inlineHelpText>First Name of the candidate</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last Name of the candidate</description>
        <externalId>true</externalId>
        <inlineHelpText>Last Name of the candidate</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/send_email_test_class.cls
@isTest
public class send_email_test_class {

    static Candidate__c c;
    public static void init()
    {
        for(integer i=0;i<10;i++)
        {
           c = new Candidate__c(first_name__c='abc',last_name__c='xyz',currently_employeed__c=false,city__c='pune',email__c='abc@pqr.com');            
            c.city__c='solapur';
            insert c;
            update c;
        }
    }
    
    public static testMethod void sendEmailTest()
    {
        init();
    }
    
}