src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions</description>
    <fields>
        <fullName>Current_Employer__c</fullName>
        <description>Current Employer of the candidate</description>
        <inlineHelpText>Current Employer of the candidate</inlineHelpText>
        <label>Current Employer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First Name of the candidate</description>
        <externalId>true</externalId>
        <inlineHelpText>First Name of the candidate</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>Social Security Number of the candidate</description>
        <inlineHelpText>Social Security Number of the candidate</inlineHelpText>
        <label>SSN</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Job_Application__c.object
<CustomObject>
    <description>Represents a candidate&apos;s application to a position</description>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship of job application to candidate</description>
        <inlineHelpText>Relationship of job application to candidate</inlineHelpText>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/test_class_not_more_than_2_pos.cls
@isTest //(seealldata=true)
public class test_class_not_more_than_2_pos {

    
    public static testMethod void test_no_more_than_2_pos()
    {
        
        candidate__c candi = new Candidate__c(first_name__c='nilesh',current_employer__c='false',ssn__c='123456789');
        insert candi;
            integer count=0;
        	for(integer i=0;i<2;i++)
        	{
         		Job_Application__c ja= new Job_Application__c(Candidate__c=candi.Id);
        		//ja.Candidate__c=candi.Id;
        		System.debug('Cadidate is:'+ja.Candidate__c);
        		insert ja;
				count++;        
                
        	}
        AggregateResult cnt=[select count(candidate__r.name) total from job_application__c where candidate__r.first_name__c='nilesh'];
        //System.debug('Total is:'+(Integer)cnt.get('total'));
            System.assertEquals(2,(Integer)cnt.get('total'));
        }
    //}
    
}