src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions</description>
    <fields>
        <fullName>Currently_Employeed__c</fullName>
        <defaultValue>true</defaultValue>
        <description>checked-currently employed
unchecked- not currently employed</description>
        <inlineHelpText>checked-currently employed
unchecked- not currently employed</inlineHelpText>
        <label>Currently Employed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First Name of the candidate</description>
        <externalId>true</externalId>
        <inlineHelpText>First Name of the candidate</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last Name of the candidate</description>
        <externalId>true</externalId>
        <inlineHelpText>Last Name of the candidate</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>Social Security Number of the candidate</description>
        <inlineHelpText>Social Security Number of the candidate</inlineHelpText>
        <label>SSN</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/nameVerify.cls
@isTest
public class nameVerify {
		
    	/*negative test case data*/
        /*static Candidate__c ca = new Candidate__c(Currently_Employeed__c=false,ssn__c='111111111');
        static Candidate__c ca1 = new Candidate__c(Currently_Employeed__c=false,ssn__c='222222222');
        static Candidate__c ca2 = new Candidate__c(Currently_Employeed__c=false,ssn__c='333333333');
    */
    
    	/*positiv test case data*/
	    static Candidate__c ca = new Candidate__c(Currently_Employeed__c=false,ssn__c='111111111',first_name__c='rohit',last_name__c='joshi');
        static Candidate__c ca1 = new Candidate__c(Currently_Employeed__c=false,ssn__c='222222222',first_name__c='rohit',last_name__c='joshi');
        static Candidate__c ca2 = new Candidate__c(Currently_Employeed__c=false,ssn__c='333333333',first_name__c='rohit',last_name__c='joshi');
    public static void init()
    {
        
        insert ca;
        insert ca1;
        insert ca2;
    }
    
    public static testMethod void testIt()
    {Test.startTest();
        init();
     Test.stopTest();
    }
    
}