src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End Date from which this class is valid from</description>
        <inlineHelpText>End Date from which this class is valid from</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date from which this class is valid from</description>
        <inlineHelpText>Start Date from which this class is valid from</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Constraint_Rule__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date up to which business rule is applicable</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Objects__c</fullName>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Class__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Division__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time_Table__c</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start date from which a business rule will be applicable</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Constraint Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constraint Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Constraints_Criteria__c.object
<CustomObject>
    <description>Constraint Criteria&apos;s for this rule</description>
    <fields>
        <fullName>Constraint_Rule__c</fullName>
        <description>Related Constraint Rule</description>
        <inlineHelpText>Related Constraint Rule</inlineHelpText>
        <label>Constraint Rule</label>
        <referenceTo>Constraint_Rule__c</referenceTo>
        <relationshipLabel>Constraints Criterias</relationshipLabel>
        <relationshipName>Constraints_Criterias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <description>Criteria to be chosen for constriant</description>
        <inlineHelpText>Criteria to be chosen for constriant</inlineHelpText>
        <label>Criteria</label>
        <picklist>
            <picklistValues>
                <fullName>Division Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actual Division Count</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Values for criteria</description>
        <inlineHelpText>Values for criteria</inlineHelpText>
        <label>Value</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>provide_value_from_field__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If value to be compared is taken from salesforce field</description>
        <inlineHelpText>If value to be compared is taken from salesforce field</inlineHelpText>
        <label>provide value from field</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>value_from_field__c</fullName>
        <description>field labels from which value can be picked up for comparing crtieria</description>
        <inlineHelpText>field labels from which value can be picked up for comparing crtieria</inlineHelpText>
        <label>value from field</label>
        <picklist>
            <picklistValues>
                <fullName>Division Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actual Division Count</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Constraints Criteria</label>
    <nameField>
        <label>Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constraints Criterias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BusinessRuleUtil.cls
public class BusinessRuleUtil
{

	public static Map<id,List<Constraints_Criteria__c>> constraints =  new Map<id,List<Constraints_Criteria__c>>();
   
    public BusinessRuleUtil()
    {

    }
        
    public static List<Constraint_Rule__c> getApplicableRuleList(List<sObject> sObjectLst,String Object_Name)
    {
        List<Constraint_Rule__c> ruleList = new List<Constraint_Rule__c>();
        
        List<Date> lstStartDates  = new List<Date>();
        List<Date> lstEndDates  = new List<date>();
        
        
        	if(sObjectLst instanceof List<class__c>)
        	{
        		List<class__c> clsLst =(List<class__c>) sObjectLst;
        		for(class__c cls:clsLst)
        		{
        			lstStartDates.add(cls.start_date__c);
        			lstEndDates.add(cls.end_date__c);
        		}
        	}
        
        ruleList = [select id, name,start_date__c,end_date__c,(select id,name,Criteria__c,provide_value_from_field__c,Value__c,value_from_field__c from Constraints_Criterias__r) from Constraint_Rule__c where Objects__c=:Object_Name and start_Date__c <= :lstStartDates and end_Date__c >= :lstEndDates];
        
        for(Constraint_Rule__c rule:ruleList)
        {
        		constraints.put(rule.id,rule.Constraints_Criterias__r);
        }
        
        
        if(ruleList.size()>0)
        {
                //throw new CustomSettingException(String.format(System.Label.NO_CRUD_FLS, arguments));
            //throw new CustomSettingException('Error: Rules Exists');
            System.debug('Error:Rule List:'+ruleList);
            validationErrors(sObjectLst,ruleList);
        }
        
        return ruleList;
    }    
    
    public static List<String> validationErrors(List<sObject> sObjectLst,List<Constraint_Rule__c> ruleList)
    {
    	if(sObjectLst instanceof List<class__c>)
        	{
        		List<class__c> clsLst =(List<class__c>) sObjectLst;
        		
        		
        		for(Constraint_Rule__c rule:ruleList)
        		{
        			List<Constraints_Criteria__c> criterias = constraints.get(rule.id);
        			
        			for(Constraints_Criteria__c criteria:criterias)
        			{
        		Map<String, Schema.SObjectField> objectFields = Schema.getGlobalDescribe().get('heylightning__Constraints_Criteria__c').getDescribe().fields.getMap();
        				
        					for(String apiName:objectFields.keySet())
        					{
        						System.debug('apiName is:'+apiName);
        					}
        			}
        		}
        		
        	
        	}
			return null;			 
    }

}