src/objects/Division__c.object
<CustomObject>
    <description>Divisions that comes under certain classes/standards</description>
    <fields>
        <fullName>attendance_reported__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Will be checked on when attendance for the day is reported. User will not be able to re-report the attendance for the same day for the same division, if this is checked</description>
        <inlineHelpText>Will be checked on when attendance for the day is reported. User will not be able to re-report the attendance for the same day for the same division, if this is checked</inlineHelpText>
        <label>attendance reported</label>
        <type>Checkbox</type>
    </fields>
    <label>Division</label>
    <nameField>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/changeAttendanceReportCheckBox.cls
global class changeAttendanceReportCheckBox implements Database.Batchable<sObject>
{
    
    global Database.QueryLocator start (Database.BatchableContext BC)
    {
        return Database.getQueryLocator('select attendance_reported__c from division__c');
    }
    
    global void execute(Database.BatchableContext BC, List<division__c>scope)
    {
        for(division__c div:scope)
        {
            div.attendance_reported__c = false;
        }
        
        if(scope.size()>0)
        {
            update scope;
        }
    }
    
    
    global void finish(Database.BatchableContext bc)
    {
    
    }
}