src/objects/Employee__c.object
<CustomObject>
    <description>Employee details</description>
    <fields>
        <fullName>Department__c</fullName>
        <description>Department of the employee</description>
        <inlineHelpText>Department of the employee</inlineHelpText>
        <label>Department</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Designation__c</fullName>
        <description>Designation of the employee</description>
        <inlineHelpText>Designation of the employee</inlineHelpText>
        <label>Designation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Name of the employee</description>
        <inlineHelpText>Name of the employee</inlineHelpText>
        <label>First_Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Displays last name of the employee</description>
        <inlineHelpText>Displays last name of the employee</inlineHelpText>
        <label>Last_Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/employeeform.cls
public class employeeform {

    public String getLname() {
        return lname;
    }

 
    
    public String getFname() {
        return fname;
    }


    public String fname{get;set;}
    public String lname{get;set;}
    public String designation{get;set;}
    public String department{get;set;}
    public void insertRecord()
    {
        System.debug('In display');
               System.debug('First_name:'+getFname());
        		System.debug('Last_name:'+getLname());
    	Employee__c emp = new Employee__c(First_Name__c=fname,Last_Name__c=lname,designation__c=designation,department__c=department);
        insert emp;
    	}
    
}