src/objects/Employee__c.object
<CustomObject>
    <description>Employee details</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email</description>
        <inlineHelpText>Email</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FileReadingClassxxx.cls
public with sharing class FileReadingClassxxx {
String fileContent='';
public PageReference readContent() {
fileContent = fileBody.toString();
List<string> allemails = fileContent.split(',');
Employee__c myemail = new Employee__c();
List<Employee__c> lstemails = new List<Employee__c>();
for(Integer i=0;i<allemails.size();i++)
{
myemail = new Employee__c(email__c=allemails[i]);
lstemails.add(myemail);
}
insert lstemails;
return null;
}
public blob fileBody { get; set; }
}