src/objects/Employee__c.object
<CustomObject>
    <description>Employee details</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email</description>
        <inlineHelpText>Email</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Name of the employee</description>
        <inlineHelpText>Name of the employee</inlineHelpText>
        <label>First_Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Displays last name of the employee</description>
        <inlineHelpText>Displays last name of the employee</inlineHelpText>
        <label>Last_Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Phone</description>
        <inlineHelpText>Phone</inlineHelpText>
        <label>Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee_SM__c.object
<CustomObject>
    <description>Employees for School Management</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the employee</description>
        <inlineHelpText>Email of the employee</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the employee</description>
        <inlineHelpText>First name of the employee</inlineHelpText>
        <label>First Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the employee</description>
        <inlineHelpText>Last name of the employee</inlineHelpText>
        <label>Last Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Phone of the employee</description>
        <inlineHelpText>Phone of the employee</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Staff__c.object
<CustomObject>
    <description>Staff informataion</description>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated Employee</description>
        <inlineHelpText>Associated Employee</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee_SM__c</referenceTo>
        <relationshipLabel>Staffs</relationshipLabel>
        <relationshipName>Staffs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First Name of staff entity</description>
        <inlineHelpText>First Name of concerned staff who is point of contact for a division</inlineHelpText>
        <label>First Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the staff entity</description>
        <inlineHelpText>Last name of the staff for a division</inlineHelpText>
        <label>Last Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Phone of the staff entity</description>
        <inlineHelpText>Last name of the staff for a division</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <description>Email of the staff entity</description>
        <inlineHelpText>Email of the staff for a division</inlineHelpText>
        <label>email</label>
        <type>Email</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StaffTriggerHandler.cls
public class StaffTriggerHandler {

    public List<Employee_SM__c> emp_list = new List<Employee_SM__c>();
    public StaffTriggerHandler()
    {

    }
    
    public void fillEmployeeDetailsAuto(List<Staff__c> staffList)
    {
        List<ID> empList = new List<ID>();
        for(Staff__c stf: staffList)
        {
            //empList+='id=:'+stf.Employee__c+', or ';
            empList.add(stf.Employee__c);
        		}
        //empList = empList.substring(0, empList.length()-1);
        
        Map<ID,Employee_SM__c> empMap = new Map<ID,Employee_SM__c> ([select name,first_name__c,last_name__c,phone__c,email__c from employee_SM__c where id= :empList]);
        List<Staff__c> stfToInsert = new List<Staff__c>();
        for(Staff__c stf: staffList)
        {
            if(empMap.containsKey(stf.Employee__c))
            {
                Employee_SM__c emp = empMap.get(stf.Employee__c);
                stf.name=emp.Name;
                stf.first_name__c = emp.First_Name__c;
                stf.last_name__c = emp.Last_Name__c;
                stf.phone__c = emp.Phone__c;
                stf.email__c = emp.Email__c;
                
        //        stfTooInsert.add(stf);
            }
        }
        
        
    }
    
    
}