src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <picklist>
            <picklistValues>
                <fullName>Gold Coast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester CD office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moorgate HO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moorgate HO - 3111</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portugal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain - ES1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain - ES2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain - ES3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain - ES4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain - Head Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain - Mallorca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TorFX - Penzance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>France</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country_of_interest__c</fullName>
        <description>Country of interest for transaction</description>
        <inlineHelpText>Country of interest for transaction</inlineHelpText>
        <label>Country of interest</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burkina Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burundi</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <description>Type of the lead</description>
        <inlineHelpText>Type of the lead</inlineHelpText>
        <label>type</label>
        <picklist>
            <picklistValues>
                <fullName>Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/SearchingSortedDemoController.cls
public class SearchingSortedDemoController
{

    public lead l{get;set;}
    public List<SelectOption> getCountries{get;set;}
    public List<SelectOption> getLeadTypes{get;set;}
    public List<SelectOption> getBranches{get;set;}
    public List<SelectOption> getSortingOptions{get;set;}

    public String selectedSortOrder{get;set;}

    public SearchingSortedDemoController()
    {
        l = new lead();
        getCountries();
        getLeadTypes();
        getBranches();
        getSortingOptions();
    }
    
    public List<SelectOption> getCountries()
    {
          List<SelectOption> options = new List<SelectOption>();
        
           Schema.DescribeFieldResult fieldResult = lead.Country_of_interest__c.getDescribe();
           List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
           for( Schema.PicklistEntry f : ple)
           {
              options.add(new SelectOption(f.getLabel(), f.getValue()));
           }       
           return options;
    }
    
    public List<SelectOption> getLeadTypes()
    {
          List<SelectOption> options = new List<SelectOption>();
        
           Schema.DescribeFieldResult fieldResult = lead.type__c.getDescribe();
           List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
           for( Schema.PicklistEntry f : ple)
           {
              options.add(new SelectOption(f.getLabel(), f.getValue()));
           }       
           return options;
    }
    
    public List<SelectOption> getBranches()
    {
          List<SelectOption> options = new List<SelectOption>();
        
           Schema.DescribeFieldResult fieldResult = lead.branch__c.getDescribe();
           List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
           for( Schema.PicklistEntry f : ple)
           {
              options.add(new SelectOption(f.getLabel(), f.getValue()));
           }       
           return options;
    }
    
    public List<SelectOption> getSortingOptions()
    {
          List<SelectOption> options = new List<SelectOption>();
        
            options.add(new SelectOption('Ascending', 'Ascending'));
            options.add(new SelectOption('Descending', 'Descending'));
          
          return options;
    }
    
    
    
}