src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CratedBy__c</fullName>
        <formula>CreatedBy.FirstName+&apos; &apos;+CreatedBy.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CratedBy</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastModified__c</fullName>
        <formula>LastModifiedBy.FirstName+&quot; &quot;+ LastModifiedBy.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LastModified</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>birthdate__c</fullName>
        <description>birthdate</description>
        <inlineHelpText>birthdate</inlineHelpText>
        <label>birthdate</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/MyJavaScriptDemo.cls
public with sharing class MyJavaScriptDemo {

    public MyJavaScriptDemo() {

    }



public Lead l{get;set;}
    public boolean showoutput{get;set;}
    public boolean showinput{get;set;}
    public boolean edit{get;set;}
    public boolean save{get;set;}


    public MyJavaScriptDemo(ApexPages.StandardController controller) {
getInfo();
showoutput=true;
showinput=false;
    }


    
    
   
    public Lead getInfo()
    {
        String recId=apexPages.currentPage().getParameters().get('id');
        
               l = [select firstname,lastname,email,phone,company,createddate,CratedBy__c,LastModified__c,ownerid,fax,birthdate__c,MobilePhone,title,rating from lead where id=:recid];
               
               return l;
    } 
    
    public void edit()
    {
      showinput=true;
      showoutput=false;
       System.debug('showinput:'+showinput);
       System.debug('showoutput:'+showoutput);
        
    }
    
    public void save()
    {
       update l;
        showoutput=true;
        showinput=false;
       
    }

}