src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <label>User_Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CollectValue.cls
public class CollectValue {
    
    public CollectValue(ApexPages.StandardController controller) {   
    }
     public Location__c location {get;set;} 
     
    
      public void save() {
        location = new Location__c();
        User u = [select firstname from user where id=:userinfo.getuserid()];
        string username = u.firstname;
        location.User_Name__c=username;
        location.Name='BNT SOFT';
        location.Latitude__c='18.5673214';
        location.Longitude__c='73.8245493';
        insert location;
      
        }

}