src/objects/Position__c.object
<CustomObject>
    <description>This object stores information about the open job positions at our company.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the current status of the position</description>
        <inlineHelpText>Shows the current status of the position</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Position No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position  Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/setPositionStatus.cls
global class setPositionStatus {

       webservice static String markOpenApproved(String positionId) {    
        //get the lead
        Position__c l = new Position__c();        
       l = [select id,status__c from position__c where id =:positionId];
       
            //l.status__c = 'Open - Approved';
            //update Status value on the position
             if(l.status__c == 'New Position No') {
                l.status__c = 'Open - Approved';
             }
            update l; 
        
        return '/' + positionId; // take us back to the refreshed page
     }

    
}